HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /l-31 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fea6c1d9be0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /l-35 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fea6c1d9c88>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /lm-18 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fea6c1d9780>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /lm-40 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fea6c1d9ef0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /l-31 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f971808de48>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /l-35 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f971808ddd8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /lm-18 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f971808dd30>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /lm-40 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f971808deb8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
'NoneType' object has no attribute 'find_all'
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-ele (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9718972438>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-9 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9718972d68>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-inf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f97189724a8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-25 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9718972d68>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-28 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f97189724a8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-29 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f96f3efca20>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-27 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f96f3efc978>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-32 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f97189720b8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-ele (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f97180a9c18>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-9 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f97180a9128>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-inf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f97180a9c18>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-25 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f97180a9d68>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-28 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f97180a9278>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-29 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f97180a9b00>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-27 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f97180a9d68>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-32 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f97189c7860>: Failed to establish a new connection: [Errno -2] Name or service not known',))
Flood control exceeded. Retry in 9.0 seconds -298020067
Flood control exceeded. Retry in 3.0 seconds -298020067
Flood control exceeded. Retry in 35.0 seconds -298020067
Flood control exceeded. Retry in 21.0 seconds -298020067
Flood control exceeded. Retry in 20.0 seconds -298020067
Flood control exceeded. Retry in 18.0 seconds -298020067
Flood control exceeded. Retry in 17.0 seconds -298020067
Flood control exceeded. Retry in 15.0 seconds -298020067
Flood control exceeded. Retry in 29.0 seconds -298020067
Flood control exceeded. Retry in 28.0 seconds -298020067
Flood control exceeded. Retry in 26.0 seconds -298020067
Flood control exceeded. Retry in 25.0 seconds -298020067
Flood control exceeded. Retry in 24.0 seconds -298020067
Flood control exceeded. Retry in 22.0 seconds -298020067
Flood control exceeded. Retry in 21.0 seconds -298020067
Flood control exceeded. Retry in 9.0 seconds -298020067
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /l-31 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6a30162fd0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /l-35 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6a300f1080>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /lm-18 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6a30162e10>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /lm-40 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6a30162be0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
'NoneType' object has no attribute 'find_all'
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-ele (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6a28122ef0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-9 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6a28119e80>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-inf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6a28119e80>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-25 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6a28119358>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-28 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6a28119a20>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-29 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6a28119eb8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-27 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6a28119e80>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-32 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6a28119240>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-ele (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6a30116780>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-9 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6a301165f8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-inf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6a301167f0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-25 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6a301166a0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-28 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6a30116908>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-29 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6a0bf99c88>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-27 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6a3012f400>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-32 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6a3012f588>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /l-31 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff2c40c06d8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /l-35 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff2c40c0668>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /lm-18 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff2c40c05c0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /lm-40 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff2c40c0748>: Failed to establish a new connection: [Errno -2] Name or service not known',))
'NoneType' object has no attribute 'find_all'
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-ele (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff2ae4e2860>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-9 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff2ae5c5160>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-inf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff2ae5c5160>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-25 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff2c70203c8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-28 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff2c7020128>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-29 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff2c70209b0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-27 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff2c7020f98>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-32 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff2c7020128>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-ele (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff2ae4f7ac8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-9 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff2ae4f7a58>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-inf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff2ae4f7b70>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-25 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff2ae4f7b38>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-28 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff2ae4f78d0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-29 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff2ae48b5c0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-27 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff2ae64a828>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-32 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff2ae4f7940>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /l-31 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3c8841cef0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /l-35 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3c8841ce80>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /lm-18 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3c8841ce48>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /lm-40 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3c883ad080>: Failed to establish a new connection: [Errno -2] Name or service not known',))
'NoneType' object has no attribute 'find_all'
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-ele (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3c8b395c50>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-9 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3c8b395d68>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-inf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3c8b395da0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-25 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3c8b395c50>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-28 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3c8b3957b8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-29 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3c8b395d68>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-27 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3c8b395c50>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-32 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3c8b3957b8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-ele (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3c8806b9b0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-9 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3c8806b828>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-inf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3c8806ba20>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-25 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3c8806b8d0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-28 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3c8806bb38>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-29 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3c882373c8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-27 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3c880400f0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-32 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3c88040898>: Failed to establish a new connection: [Errno -2] Name or service not known',))
'NoneType' object has no attribute 'find_all'
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /l-31 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feeb811da20>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /l-35 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feeb811d9b0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /lm-18 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feeb811d908>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /lm-40 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feeb811da90>: Failed to establish a new connection: [Errno -2] Name or service not known',))
'NoneType' object has no attribute 'find_all'
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-ele (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feeb0748c50>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-9 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feeb0748ba8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-inf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feeb0748ac8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-25 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feeb91c5a20>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-28 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feeb91c5da0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-29 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feeb91c5f60>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-27 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feeb91c5a20>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-32 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feeb91c5da0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-ele (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feeb809b358>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-9 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feeb809b198>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-inf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feeb809b240>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-25 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feeb809b198>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-28 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feeb809b2e8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-29 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feeb05f0ac8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-27 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feeb91d2ba8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-32 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feeb09befd0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /l-31 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feb3001f320>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /l-35 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feb3001f2b0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /lm-18 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feb3001f208>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /lm-40 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feb3001f320>: Failed to establish a new connection: [Errno -2] Name or service not known',))
'NoneType' object has no attribute 'find_all'
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-ele (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feb30017fd0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-9 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feb30017588>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-inf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feb30017b38>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-25 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feb30017400>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-28 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feb30017b38>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-29 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feb30017588>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-27 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feb30017400>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-32 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feb30017b38>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-ele (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feb21f51390>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-9 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feb21f512e8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-inf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feb21f51400>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-25 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feb21f51550>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-28 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feb21f512e8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-29 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feb21fa6908>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-27 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feb21dc77b8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-32 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feb21f43f98>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /l-31 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcf7044bc88>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /l-35 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcf7044bc18>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /lm-18 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcf7044bb70>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /lm-40 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcf7044bcf8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
'NoneType' object has no attribute 'find_all'
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-ele (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcf7027fc50>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-9 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcf7027fac8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-inf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcf700b9b00>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-25 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcf700b9a90>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-28 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcf700b9a20>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-29 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcf700b9f28>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-27 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcf700b9a90>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-32 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcf700b9588>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-ele (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcf702573c8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-9 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcf70257208>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-inf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcf70257160>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-25 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcf702570b8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-28 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcf702572b0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-29 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcf70038748>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-27 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcf7008ed68>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-32 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcf7008ef60>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /l-31 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5f8c75a908>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /l-35 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5f8c75a898>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /lm-18 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5f8c75a7f0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /lm-40 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5f8c75a978>: Failed to establish a new connection: [Errno -2] Name or service not known',))
'NoneType' object has no attribute 'find_all'
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-ele (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5f8c70fc18>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-9 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5f8c70fa90>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-inf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5f8e6556d8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-25 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5f8e6550f0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-28 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5f8e655f60>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-29 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5f8e655eb8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-27 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5f8e6552b0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-32 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5f8e655c50>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-ele (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5f8c70c278>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-9 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5f8c70c160>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-inf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5f8c70c400>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-25 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5f8c70c390>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-28 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5f8c70c160>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-29 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5f8c5ef3c8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-27 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5f8c338668>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-32 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5f8c338be0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /l-31 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f349c217198>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /l-35 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f349c21ad30>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /lm-18 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f349c217160>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /lm-40 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f349c217128>: Failed to establish a new connection: [Errno -2] Name or service not known',))
'NoneType' object has no attribute 'find_all'
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /l-31 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f349c11dfd0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /l-35 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f349c11def0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /lm-18 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f349c11dc18>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /lm-40 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f349c11de80>: Failed to establish a new connection: [Errno -2] Name or service not known',))
'NoneType' object has no attribute 'find_all'
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-ele (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f34865c07f0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-9 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f34865c04e0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-inf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f349c1d9ac8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-25 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f348652bb00>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-28 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f348652b978>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-29 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f348652b668>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-27 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f348652bb00>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-32 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f348652b978>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-ele (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f348673ab00>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-9 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f348673a710>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-inf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f348673a588>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-25 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f348673a438>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-28 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f348673a588>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-29 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f348673a710>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-27 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f348673a438>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-32 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f348673a588>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /l-31 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7eccb41080>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /l-35 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7eccb41358>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /lm-18 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7eccb41470>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /lm-40 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7eccb41828>: Failed to establish a new connection: [Errno -2] Name or service not known',))
'NoneType' object has no attribute 'find_all'
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /l-31 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7eccb5bb00>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /l-35 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7eccb5b908>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /lm-18 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7eccb5bd30>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /lm-40 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7eccb5bb70>: Failed to establish a new connection: [Errno -2] Name or service not known',))
'NoneType' object has no attribute 'find_all'
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-ele (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7ecc8b9f28>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-9 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7ecc8b9da0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-inf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7ecc84fa20>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-25 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7ecc8b9cc0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-28 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7ecc8b9c88>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-29 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7ecc8b99e8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-27 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7ecc8b9dd8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-32 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7ecc8b9c88>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-ele (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7ecc92bb00>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-9 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7ecc92b400>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-inf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7ecc92b898>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-25 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7ecc92b588>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-28 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7ecc92b518>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-29 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7ecc92b358>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-27 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7ecc92b2b0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-32 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7ecc92b358>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /l-31 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fee68383240>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /l-35 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fee68383160>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /lm-18 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fee68370f60>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /lm-40 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fee68370d30>: Failed to establish a new connection: [Errno -2] Name or service not known',))
'NoneType' object has no attribute 'find_all'
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /l-31 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fee681f7780>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /l-35 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fee681f7588>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /lm-18 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fee681f75c0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /lm-40 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fee681f7748>: Failed to establish a new connection: [Errno -2] Name or service not known',))
'NoneType' object has no attribute 'find_all'
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-ele (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fee682b2828>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-9 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fee682b2780>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-inf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fee682b2f98>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-25 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fee682b2940>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-28 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fee682b26d8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-29 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fee682b2780>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-27 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fee682b2940>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-32 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fee682b26d8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-ele (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fee681c5320>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-9 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fee681c5390>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-inf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fee681c52b0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-25 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fee681c5390>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-28 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fee681c52b0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-29 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fee682f1c88>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-27 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fee681c52b0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-32 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fee682f1f60>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /l-31 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdcc067ecc0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /l-35 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdcc067ef98>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /lm-18 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdcc067ed68>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /lm-40 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdcc0680fd0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
'NoneType' object has no attribute 'find_all'
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /l-31 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdcc04f4780>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /l-35 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdcc04f4588>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /lm-18 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdcc04f45c0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /lm-40 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdcc04f4748>: Failed to establish a new connection: [Errno -2] Name or service not known',))
'NoneType' object has no attribute 'find_all'
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-ele (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdcc05c7710>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-9 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdcc05c76d8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-inf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdcc053d048>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-25 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdcc05c7710>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-28 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdcc05c77b8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-29 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdcc05c7668>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-27 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdcc05c7978>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-32 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdcc05c7630>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-ele (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdcc250ccc0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-9 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdcc250c8d0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-inf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdcc250ce48>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-25 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdcc250c9b0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-28 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdcc250c8d0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-29 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdcc250ce48>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-27 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdcc250cc88>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-32 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdcc250c278>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /l-31 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f09786b7390>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /l-35 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f09786b7470>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /lm-18 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f09786b7668>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /lm-40 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f09786b7390>: Failed to establish a new connection: [Errno -2] Name or service not known',))
'NoneType' object has no attribute 'find_all'
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /l-31 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0978644b38>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /l-35 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0978644d68>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /lm-18 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0978644a90>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /lm-40 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0978644ac8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
'NoneType' object has no attribute 'find_all'
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-ele (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f09785e8e80>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-9 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f09785e8dd8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-inf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0978653f98>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-25 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f09785e8ba8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-28 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f09785e8c50>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-29 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f09785e8c18>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-27 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f09785e8f28>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-32 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f09785e8c50>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-ele (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f09783ec7b8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-9 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f09783ecc18>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-inf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f09783ecc18>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-25 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f09782d4780>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-28 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f09783ec748>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-29 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f097c62d208>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-27 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f09783ec748>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-32 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0978426518>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /l-31 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f556875d1d0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /l-35 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f556875d048>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /lm-18 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5568758f60>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /lm-40 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5568758fd0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
'NoneType' object has no attribute 'find_all'
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /l-31 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f55685d1748>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /l-35 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f55685d1550>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /lm-18 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f55685d1588>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /lm-40 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f55685d1710>: Failed to establish a new connection: [Errno -2] Name or service not known',))
'NoneType' object has no attribute 'find_all'
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-ele (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5568758978>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-9 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5568758fd0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-inf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5568758ef0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-25 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5568758908>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-28 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5568758f60>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-29 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5568758f98>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-27 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5568758908>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-32 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5568758f60>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-ele (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f556b5e6ba8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-9 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f556b5e6fd0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-inf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f556b5e6828>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-25 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f556b5e6f28>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-28 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f556b5e6fd0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-29 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f556b5e6828>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-27 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f556b5e6748>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-32 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f556b5e6b00>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /l-31 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6eb0252240>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /l-35 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6eb0252128>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /lm-18 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6eb02521d0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /lm-40 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6eb0254f98>: Failed to establish a new connection: [Errno -2] Name or service not known',))
'NoneType' object has no attribute 'find_all'
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /l-31 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6eb00d5710>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /l-35 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6eb00d5518>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /lm-18 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6eb00d5550>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /lm-40 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6eb00d56d8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
'NoneType' object has no attribute 'find_all'
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-ele (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6eb0213860>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-9 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6eb02135c0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-inf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6eb0213668>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-25 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6eb02137f0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-28 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6eb0213630>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-29 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6eb0213710>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-27 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6eb0213320>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-32 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6eb0213f60>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-ele (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6eb007b4e0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-9 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6eb01eec50>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-inf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6eb01eeda0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-25 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6eb01eefd0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-28 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6eb01ee780>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-29 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6eb01eee80>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-27 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6eb007b518>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-32 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6eb007b1d0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /l-31 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f73e0240780>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /l-35 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f73e0240710>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /lm-18 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f73e02405c0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /lm-40 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f73e0240780>: Failed to establish a new connection: [Errno -2] Name or service not known',))
'NoneType' object has no attribute 'find_all'
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /l-31 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f73e0308b70>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /l-35 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f73e0308da0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /lm-18 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f73e0308ac8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /lm-40 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f73e0308b00>: Failed to establish a new connection: [Errno -2] Name or service not known',))
'NoneType' object has no attribute 'find_all'
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-ele (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f73e0218470>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-9 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f73e0218f28>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-inf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f73c3ec2748>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-25 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f73e028f1d0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-28 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f73e02189e8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-29 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f73e0218f28>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-27 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f73e0218748>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-32 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f73e02189e8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-ele (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f73c3f0fb38>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-9 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f73c3f0fac8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-inf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f73c3f0f828>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-25 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f73c3f0fc18>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-28 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f73c3f0f0b8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-29 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f73c3e81898>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-27 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f73c3f0fc18>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-32 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f73c3f0f0f0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /l-31 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0cec56a160>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /l-35 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0cec55ccf8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /lm-18 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0cec55cf60>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /lm-40 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0cec56a128>: Failed to establish a new connection: [Errno -2] Name or service not known',))
'NoneType' object has no attribute 'find_all'
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /l-31 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0cec3de710>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /l-35 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0cec3de518>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /lm-18 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0cec3de550>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /lm-40 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0cec3de6d8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
'NoneType' object has no attribute 'find_all'
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-ele (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0cec406710>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-9 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0cec4066a0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-inf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0cec406550>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-25 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0cec4062e8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-28 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0cec406390>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-29 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0cec406828>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-27 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0cec406588>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-32 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0cec406f60>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-ele (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0cef3f3f28>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-9 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0cef3f3fd0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-inf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0cef3f34e0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-25 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0cef3f3c50>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-28 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0cef3f3c88>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-29 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0cef3f3198>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-27 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0cef3f3c88>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-32 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0cef3f34e0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /l-31 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f54c8b04390>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /l-35 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f54c8b04470>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /lm-18 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f54c8b04668>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /lm-40 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f54c8b04390>: Failed to establish a new connection: [Errno -2] Name or service not known',))
'NoneType' object has no attribute 'find_all'
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /l-31 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f54c8bc8b38>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /l-35 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f54c8bc8940>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /lm-18 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f54c8bc8d68>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /lm-40 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f54c8bc8ba8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
'NoneType' object has no attribute 'find_all'
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-ele (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f54c8ae2eb8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-9 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f54c8ae2cf8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-inf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f54c8b53278>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-25 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f54c8a8c710>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-28 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f54c8ae2cc0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-29 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f54c8ae2dd8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-27 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f54c8ae2c18>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-32 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f54c8ae2ba8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-ele (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f54c87ce1d0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-9 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f54c87cec50>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-inf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f54c87cecc0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-25 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f54c87ced68>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-28 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f54c87cec50>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-29 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f54c87cecc0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-27 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f54c87cec18>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-32 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f54c87ce3c8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /l-31 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7facb8045518>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /l-35 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7facb80fe6d8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /lm-18 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7facb80fe748>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /lm-40 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7facb80fe6a0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
'NoneType' object has no attribute 'find_all'
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /l-31 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7faca2fc3dd8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /l-35 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7faca2fc3c50>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /lm-18 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7faca2fc3ac8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /lm-40 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7faca2fc3518>: Failed to establish a new connection: [Errno -2] Name or service not known',))
'NoneType' object has no attribute 'find_all'
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-ele (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7faca2d8bd68>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-9 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7faca2d8bda0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-inf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7facb808d198>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-25 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7faca2fe1eb8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-28 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7faca2d8bdd8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-29 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7faca2d8be48>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-27 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7faca2d8bc18>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-32 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7faca2d8bcc0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-ele (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7faca2ea7898>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-9 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7faca2ea7978>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-inf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7faca2ea7588>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-25 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7faca2ea7dd8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-28 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7faca2ea7550>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-29 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7faca2de8588>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-27 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7faca2ea73c8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-32 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7faca2ea7438>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /l-31 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5b9411b240>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /l-35 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5b9411b160>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /lm-18 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5b9412bf60>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /lm-40 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5b9412bd30>: Failed to establish a new connection: [Errno -2] Name or service not known',))
'NoneType' object has no attribute 'find_all'
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /l-31 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5b77772780>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /l-35 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5b77772588>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /lm-18 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5b777725c0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /lm-40 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5b77772748>: Failed to establish a new connection: [Errno -2] Name or service not known',))
'NoneType' object has no attribute 'find_all'
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-ele (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5b777ef3c8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-9 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5b777ef198>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-inf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5b777efbe0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-25 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5b777ef1d0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-28 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5b777ef358>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-29 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5b777efbe0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-27 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5b777ef1d0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-32 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5b777ef358>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-ele (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5b97fb1940>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-9 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5b97fb10b8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-inf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5b97ffca20>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-25 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5b97fb19b0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-28 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5b97ffc630>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-29 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5b7753ff98>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-27 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5b97ffc7b8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-32 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5b7753fe80>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /l-31 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f60f0766ef0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /l-35 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f60f075ae80>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /lm-18 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f60f075acc0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /lm-40 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f60f075af98>: Failed to establish a new connection: [Errno -2] Name or service not known',))
'NoneType' object has no attribute 'find_all'
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /l-31 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f60f05db6d8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /l-35 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f60f05db4e0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /lm-18 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f60f05db518>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /lm-40 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f60f05db6a0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
'NoneType' object has no attribute 'find_all'
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-ele (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f60f0652048>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-9 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f60f02da630>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-inf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f60f06526a0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-25 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f60f06525c0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-28 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f60f02da6d8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-29 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f60f02da748>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-27 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f60f02da6a0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-32 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f60f02da630>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-ele (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f60f0721630>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-9 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f60f0721588>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-inf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f60f0721f60>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-25 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f60f0721278>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-28 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f60f0721160>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-29 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f60f0721f60>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-27 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f60f0721f98>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-32 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f60f0721f60>: Failed to establish a new connection: [Errno -2] Name or service not known',))
