HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /l-31 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fea6c1d9be0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /l-35 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fea6c1d9c88>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /lm-18 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fea6c1d9780>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /lm-40 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fea6c1d9ef0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
