HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /l-31 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fea6c1d9be0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /l-35 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fea6c1d9c88>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /lm-18 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fea6c1d9780>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /lm-40 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fea6c1d9ef0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /l-31 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f971808de48>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /l-35 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f971808ddd8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /lm-18 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f971808dd30>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /lm-40 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f971808deb8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
'NoneType' object has no attribute 'find_all'
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-ele (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9718972438>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-9 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9718972d68>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-inf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f97189724a8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-25 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9718972d68>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-28 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f97189724a8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-29 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f96f3efca20>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-27 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f96f3efc978>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-32 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f97189720b8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-ele (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f97180a9c18>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-9 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f97180a9128>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-inf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f97180a9c18>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-25 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f97180a9d68>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-28 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f97180a9278>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-29 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f97180a9b00>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-27 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f97180a9d68>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-32 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f97189c7860>: Failed to establish a new connection: [Errno -2] Name or service not known',))
Flood control exceeded. Retry in 9.0 seconds -298020067
Flood control exceeded. Retry in 3.0 seconds -298020067
Flood control exceeded. Retry in 35.0 seconds -298020067
Flood control exceeded. Retry in 21.0 seconds -298020067
Flood control exceeded. Retry in 20.0 seconds -298020067
Flood control exceeded. Retry in 18.0 seconds -298020067
Flood control exceeded. Retry in 17.0 seconds -298020067
Flood control exceeded. Retry in 15.0 seconds -298020067
Flood control exceeded. Retry in 29.0 seconds -298020067
Flood control exceeded. Retry in 28.0 seconds -298020067
Flood control exceeded. Retry in 26.0 seconds -298020067
Flood control exceeded. Retry in 25.0 seconds -298020067
Flood control exceeded. Retry in 24.0 seconds -298020067
Flood control exceeded. Retry in 22.0 seconds -298020067
Flood control exceeded. Retry in 21.0 seconds -298020067
Flood control exceeded. Retry in 9.0 seconds -298020067
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /l-31 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6a30162fd0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /l-35 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6a300f1080>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /lm-18 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6a30162e10>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /lm-40 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6a30162be0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
'NoneType' object has no attribute 'find_all'
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-ele (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6a28122ef0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-9 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6a28119e80>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-inf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6a28119e80>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-25 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6a28119358>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-28 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6a28119a20>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-29 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6a28119eb8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-27 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6a28119e80>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-32 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6a28119240>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-ele (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6a30116780>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-9 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6a301165f8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-inf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6a301167f0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-25 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6a301166a0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-28 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6a30116908>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-29 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6a0bf99c88>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-27 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6a3012f400>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-32 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6a3012f588>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /l-31 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff2c40c06d8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /l-35 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff2c40c0668>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /lm-18 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff2c40c05c0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /lm-40 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff2c40c0748>: Failed to establish a new connection: [Errno -2] Name or service not known',))
'NoneType' object has no attribute 'find_all'
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-ele (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff2ae4e2860>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-9 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff2ae5c5160>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-inf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff2ae5c5160>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-25 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff2c70203c8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-28 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff2c7020128>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-29 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff2c70209b0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-27 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff2c7020f98>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-32 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff2c7020128>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-ele (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff2ae4f7ac8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-9 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff2ae4f7a58>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-inf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff2ae4f7b70>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-25 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff2ae4f7b38>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-28 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff2ae4f78d0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-29 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff2ae48b5c0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-27 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff2ae64a828>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-32 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff2ae4f7940>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /l-31 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3c8841cef0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /l-35 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3c8841ce80>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /lm-18 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3c8841ce48>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /lm-40 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3c883ad080>: Failed to establish a new connection: [Errno -2] Name or service not known',))
'NoneType' object has no attribute 'find_all'
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-ele (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3c8b395c50>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-9 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3c8b395d68>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-inf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3c8b395da0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-25 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3c8b395c50>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-28 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3c8b3957b8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-29 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3c8b395d68>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-27 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3c8b395c50>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-32 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3c8b3957b8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-ele (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3c8806b9b0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-9 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3c8806b828>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-inf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3c8806ba20>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-25 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3c8806b8d0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-28 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3c8806bb38>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-29 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3c882373c8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-27 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3c880400f0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-32 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3c88040898>: Failed to establish a new connection: [Errno -2] Name or service not known',))
'NoneType' object has no attribute 'find_all'
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /l-31 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feeb811da20>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /l-35 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feeb811d9b0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /lm-18 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feeb811d908>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /lm-40 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feeb811da90>: Failed to establish a new connection: [Errno -2] Name or service not known',))
'NoneType' object has no attribute 'find_all'
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-ele (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feeb0748c50>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-9 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feeb0748ba8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-inf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feeb0748ac8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-25 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feeb91c5a20>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-28 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feeb91c5da0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-29 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feeb91c5f60>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-27 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feeb91c5a20>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-32 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feeb91c5da0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-ele (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feeb809b358>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-9 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feeb809b198>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-inf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feeb809b240>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-25 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feeb809b198>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-28 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feeb809b2e8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-29 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feeb05f0ac8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-27 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feeb91d2ba8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-32 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feeb09befd0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /l-31 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feb3001f320>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /l-35 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feb3001f2b0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /lm-18 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feb3001f208>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /lm-40 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feb3001f320>: Failed to establish a new connection: [Errno -2] Name or service not known',))
'NoneType' object has no attribute 'find_all'
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-ele (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feb30017fd0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-9 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feb30017588>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-inf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feb30017b38>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-25 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feb30017400>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-28 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feb30017b38>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-29 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feb30017588>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-27 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feb30017400>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-32 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feb30017b38>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-ele (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feb21f51390>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-9 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feb21f512e8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-inf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feb21f51400>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-25 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feb21f51550>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-28 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feb21f512e8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-29 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feb21fa6908>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-27 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feb21dc77b8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-32 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feb21f43f98>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /l-31 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcf7044bc88>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /l-35 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcf7044bc18>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /lm-18 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcf7044bb70>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /lm-40 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcf7044bcf8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
'NoneType' object has no attribute 'find_all'
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-ele (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcf7027fc50>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-9 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcf7027fac8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-inf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcf700b9b00>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-25 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcf700b9a90>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-28 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcf700b9a20>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-29 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcf700b9f28>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-27 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcf700b9a90>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-32 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcf700b9588>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-ele (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcf702573c8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-9 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcf70257208>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-inf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcf70257160>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-25 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcf702570b8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-28 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcf702572b0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-29 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcf70038748>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-27 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcf7008ed68>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-32 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcf7008ef60>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /l-31 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5f8c75a908>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /l-35 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5f8c75a898>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /lm-18 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5f8c75a7f0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='web.dmi.unict.itcorsi', port=80): Max retries exceeded with url: /lm-40 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5f8c75a978>: Failed to establish a new connection: [Errno -2] Name or service not known',))
'NoneType' object has no attribute 'find_all'
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-ele (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5f8c70fc18>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-9 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5f8c70fa90>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-inf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5f8e6556d8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-25 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5f8e6550f0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-28 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5f8e655f60>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-29 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5f8e655eb8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-27 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5f8e6552b0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-32 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5f8e655c50>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-ele (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5f8c70c278>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-9 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5f8c70c160>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /l-8-inf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5f8c70c400>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-25 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5f8c70c390>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-28 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5f8c70c160>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-29 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5f8c5ef3c8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-27 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5f8c338668>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPConnectionPool(host='www.dieei.unict.itcorsi', port=80): Max retries exceeded with url: /lm-32 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5f8c338be0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
